# Generated by Django 2.1 on 2018-08-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=10, default=None, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=None, max_digits=20)),
                ('rating', models.DecimalField(decimal_places=10, default=None, max_digits=20)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddelivery.Restaurant'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='restaurant_id',
            field=models.ManyToManyField(related_name='cuisines', to='fooddelivery.Restaurant'),
        ),
    ]
